### ISSUE TITLE
QueryProcessingError: Invoice Email Validation

### ISSUE THREAD

**Issue by davidseywald** [intuit/QuickBooks-V3-Java-SDK#47]
Hello,
We updated from 5.0.1 to 5.0.2 and now we get this error message:

`{"Fault":{"Error":[{"Message":"Error processing query","Detail":"QueryProcessingError: To email address entered is invalid","code":"4002"}],"type":"Service"},"time":"2019-03-06T01:17:20.232-08:00"}`

It seems, it is possible to enter invalid email addresses in Invoices UI, but still save them, which causes then problems in API calls. 

Could you please check/advise how to handle this?
Thank you.

**Comment by diana-derose** [comment]
Hi @davidseywald  - Can you share your request or email that you used. The error is probably not SDK related.

**Comment by davidseywald** [comment]
@diana-derose I can reproduce that it works with 5.0.1 and does not work with 5.0.2 (maybe some validation was added?).

We are trying to get changed Invoices, via `executeCDCQuery`.
Since we do not have access to the QBO Company (only OAuth), we cannot check the invoice data.

**Comment by diana-derose** [comment]
Are you able to enable logging and capture intuit_tid from the response header? If not, can you share the company id and the timestamp of the error, i can try to look through the logs. 

Also, try one more thing - using v5.0.2 set the minor version to 35 context.setMinorVersion("35"); and then see if you still get the error.

**Comment by davidseywald** [comment]
The companyId/realmid is: 123145774565544
Time was: 2019-03-06T01:17:20.232-08:00

Updating the Sdk, but setting minorVersion to 35 seems to solve the problem.
Thank you.

**Comment by diana-derose** [comment]
Thanks, this looks like an error in the API, I have filed a bug with the team to troubleshoot this. Here is the bug id (PLEX-1263) for your reference. Will keep you updated on their progress, in the meantime please continue to use minor version 35.

**Comment by diana-derose** [comment]
Hi @davidseywald  - Update on this bug. This happens when invoices have multiple email addresses associated with it. This is getting fixed on April 9th. I am closing this issue since it doesn't require any SDK updates.

**Comment by davidseywald** [comment]
Hi @diana-derose,
We updated to latest Version 5.0.3, latest minor version and getting the same error with another company, when getting Invoice data.

2019-04-10 08:00:58.878: ERROR CODE:4002, ERROR MESSAGE:Error processing query, ERROR DETAIL:QueryProcessingError: To email address entered is invalid

Could you please advice/re-check? Thank you.

**Comment by diana-derose** [comment]
Hi @davidseywald - Looks like the release was on hold due to internal code freeze (tax season), it is scheduled to go out on Apr 23rd. I'll keep this issue open and let you know when you can test. Sorry about that.

**Comment by diana-derose** [comment]
@davidseywald  - Can you give it a try now?

**Comment by davidseywald** [comment]
@diana-derose We are still getting the same error message:
com.intuit.ipp.exception.ServiceException: ERROR CODE:4002, ERROR MESSAGE:Error processing query, ERROR DETAIL:QueryProcessingError: To email address entered is invalid

For company realm id: 193514702392054

Thank you.

**Comment by diana-derose** [comment]
Hi @davidseywald  - It looks like the changes haven't been pushed to clusters hosting Canadian companies yet due to code freeze for that region (Canadian tax season). You shouldn't see the error for non Canadian companies though. For Canadian companies the fix will go out on May 2nd.

**Comment by aaronhudon-ts** [comment]
@diana-derose I am seeing this error using the REST API, no SDK.
```

{
    "Fault": {
        "Error": [
            {
                "Message": "Error processing query",
                "Detail": "QueryProcessingError: To email address entered is invalid",
                "code": "4002"
            }
        ],
        "type": "Service"
    },
    "time": "2019-04-30T18:03:14.468-07:00"
}
```

**Comment by aaronhudon** [comment]
@diana-derose 

I am seeing this error when using the REST API.
```

{
    "Fault": {
        "Error": [
            {
                "Message": "Error processing query",
                "Detail": "QueryProcessingError: To email address entered is invalid",
                "code": "4002"
            }
        ],
        "type": "Service"
    },
    "time": "2019-04-30T18:03:14.468-07:00"
}
```

**Comment by diana-derose** [comment]
@aaronhudon  - Do you know if the company for which you are getting the error is a Canadian QuickBooks Online company? If not sure, send me your company id so I can check.

**Comment by aaronhudon** [comment]
Yes, Canadian

**Comment by diana-derose** [comment]
Thanks for confirming. See my comment above for Canadian companies, issue should be resolved after May 2nd. https://github.com/intuit/QuickBooks-V3-Java-SDK/issues/47#issuecomment-486797624

**Comment by mlatzel** [comment]
We are still seeing this issue - independent of JavaSDK. Canadian company. May 3rd. PHP SDK. Same problem as described above. @diana-derose can you confirm when fix will be out?

**Comment by diana-derose** [comment]
Hi @mlatzel - the release was pushed to today evening. I would suggest you hold off on testing, until I notify here that the fix is available.

**Comment by diana-derose** [comment]
This issue should be resolved now for all locales including Canadian companies. @davidseywald @aaronhudon @mlatzel  - can you try again to see if your issues are resolved.

**Comment by davidseywald** [comment]
@diana-derose It seems to work now, thank you!

**Comment by mlatzel** [comment]
Yes, same here, thanks @diana-derose ! I

s this a good channel to watch updates regarding the API in general? Is there a different channel you recommend?

**Comment by diana-derose** [comment]
Hi @mlatzel  - This repo is good to watch updates to the SDK. If you are interested for API updates in general then you should watch our release notes here https://developer.intuit.com/app/developer/qbo/docs/develop/release-notes/quickbooks-api-release-notes#quickbooks-online-v1909  or bug tracker https://help.developer.intuit.com/s/bug-tracker-page

**Comment by davidseywald** [comment]
Hello @diana-derose ,
Not sure if this the same issue, but we are getting the same error messages again (extracting CDC Invoices):

`ERROR CODE:4002, ERROR MESSAGE:Error processing query, ERROR DETAIL:QueryProcessingError: To email address entered is invalid`

Company realm id: 545710125
As far as I can tell this is a US based company.

We are also getting a lot of 502 Bad Gateway errors, maybe this is related?

```
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Thank you.

**Comment by diana-derose** [comment]
Hi @davidseywald  - Can you please create a ticket here since this is not SDK related. https://help.developer.intuit.com/s/contactsupport

**Comment by abdulwahidgul24085** [comment]
minor 35 change fixed it for me.
